# Generated by Django 3.1.3 on 2023-11-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0004_carro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total'),
        ),
    ]
