# Generated by Django 3.1.3 on 2023-11-09 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0006_carroproduto_pedido_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='produtos',
            new_name='produto',
        ),
    ]
