# Generated by Django 3.1.3 on 2023-11-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0007_auto_20231109_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carroproduto',
            old_name='Produto',
            new_name='produto',
        ),
    ]
