# Generated by Django 3.1.3 on 2023-11-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0008_auto_20231109_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
