# Generated by Django 3.1.3 on 2023-11-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0009_auto_20231110_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
