# Generated by Django 4.2.7 on 2023-11-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0014_alter_admin_id_alter_carro_id_alter_carroproduto_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_order',
            name='pagamento_completo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='pagamento_method',
            field=models.CharField(choices=[('Dinheiro Na Entrega', 'Dinheiro Na Entrega'), ('Khalti', 'Khalti')], default='Dinheiro Na Entrega', max_length=20),
        ),
    ]
